Repository SKKU-Online-Learning-System/mvp-frontend-nextjs, pull requests merged in 2025-03, with the labels that each got.

#21 [FEAT] 좋아요 api 연동
  src/api/content.ts
  src/app/page.tsx
  src/component/main/MainContent/MainContentCard.tsx
  src/component/main/MainContent/MainContentLike.tsx
  src/component/main/MainContent/index.ts
  src/component/video/VideoContent/VideoContainer.tsx
  src/component/video/VideoContent/VideoContentLike.tsx
  src/component/video/VideoContent/VideoInfo.tsx
  src/component/video/VideoContent/index.ts
Labels: feature, api

#23 [FEAT] 상단 바 재생목록 기능 추가
  src/app/layout.tsx
  src/component/main/MainContent/ContentCategory.tsx
  src/component/main/MainContent/MainGridContainer.tsx
  src/component/main/MainContent/category.ts
  src/component/main/MainContent/index.ts
Labels: feature

#27 [FEAT] 디자인 버그 수정
  src/app/globals.css
  src/app/layout.tsx
  src/component/common/Header/LoginButton.tsx
  src/component/common/Header/LogoutButton.tsx
  src/component/common/Header/SearchBar.tsx
  src/component/main/MainContent/MainContentCard.tsx
  src/component/main/SideBar/LeftSideBar.tsx
  src/component/main/SideBar/SideBar.tsx
  src/component/textbook/TextBookCard.tsx
Labels: bug
